spring:
  application:
    name: provider-a
server:
  port: 8082

eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
    preferIpAddress: true
    hostname: peer1
    metadata-map:
      zone: zone-1
      version: release

  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 9
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
