spring:
  application:
    name: consumer-a
  cloud:
    #高版本Spring cloud 移除了 ribbon 作为负载均衡器
    loadbalancer:
      configurations: zone-preference

server:
  port: 8083

eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
    hostname: peer1
    metadata-map:
      zone: zone-1

  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 9
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
